jetbrains://idea/navigate/reference?project=TugasPBO2_GAGAS&fqn=Matematika_Gagas3F.Matematika
C:\Users\USER\IdeaProjects\TugasPBO2_GAGAS\src\Matematika_Gagas3F\Matematika.java

package Matematika_Gagas3F;

public class Matematika{
    public static void main(String[] args) {}
    public int pertambahan(int a, int b) {
        int hasil =  a + b;
        return hasil;
    }

    public int pengurangan(int a, int b) {
        int hasil = a - b;
        return hasil;
    }

    public int perkalian(int a, int b) {
        int hasil = a * b;
        return hasil;
    }

    public int pembagian(int a, int b) {
        int hasil = a / b;
        return hasil;
    }
}
